name = "Edrobot Minecraft Mod Pack"
author = "Edrobot"
version = ".5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c00158939c50bae5d9bac8312ae4f16a7ee637198196234253834fb3ffa449"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
