name = "EMS DIFFERENT FUTURE"
author = "Edrobot"
version = "i.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ffa747e7d761b259bd9dd7477c443cf4829bf7bf51b96f6fc7a0cb937541a78"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
